-- Cílová tabulka nové aplikace. Struktura vychází z Liferay Service Builder tabulky
-- DEMO_Task (viz liferay-workspace/modules/task/task-service/src/main/resources/META-INF/sql/tables.sql):
--
--   create table DEMO_Task (taskId LONG not null primary key, groupId LONG, companyId LONG,
--       userId LONG, createDate DATE null, title VARCHAR(75) null, done BOOLEAN);
--
-- Rozdíly: snake_case názvy, NOT NULL omezení, delší title, ID z identity sekvence
-- (Liferay generuje ID přes tabulku Counter, ne přes DB sekvenci).
-- group_id / company_id / user_id zůstávají jako "legacy" reference pro dohledatelnost.
create table task
(
    id          bigint generated by default as identity primary key,
    title       varchar(255) not null,
    done        boolean      not null default false,
    create_date timestamp    not null default (now() at time zone 'utc'), -- UTC jako Liferay
    group_id    bigint,
    company_id  bigint,
    user_id     bigint
);

create index ix_task_done on task (done);
